{"name": "Проверка ошибки 404 при попытке залогинется несуществующим курьером", "status": "passed", "start": 1717960332390, "stop": 1717960332390, "uuid": "de3e65e6-40c0-4fc5-b8d0-e5901bd3ca36", "historyId": "0833f5263d6f3b7ac3031bcba2547b26", "testCaseId": "0833f5263d6f3b7ac3031bcba2547b26", "fullName": "tests.test_login_courier.TestLoginCourier#test_not_existed_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "0000NBB03CJLVCF"}, {"name": "thread", "value": "610-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}